FROM openjdk:17
MAINTAINER daily-muse-adminserver
COPY build/libs/microservice-authentication-0.0.1-SNAPSHOT.jar microservice-authentication-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/microservice-authentication-0.0.1-SNAPSHOT.jar"]