FROM openjdk:17
MAINTAINER daily-muse-adminserver
COPY build/libs/microservice-user-0.0.1-SNAPSHOT.jar microservice-user-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/microservice-user-0.0.1-SNAPSHOT.jar"]