FROM openjdk:17
MAINTAINER daily-muse-adminserver
COPY build/libs/microservice-note-0.0.1-SNAPSHOT.jar microservice-note-0.0.1-SNAPSHOT.jar
EXPOSE 8081
ENTRYPOINT ["java","-jar","/microservice-note-0.0.1-SNAPSHOT.jar"]